event_manager/deploy/eventlist/models.py
import datetime
from django.db import models
from django.contrib.auth.models import User as DjangoUser

class User(models.Model):
    user = models.OneToOneField(DjangoUser, on_delete=models.CASCADE)
    creation_date = models.DateField(auto_now_add=True)
    last_updated_date = models.DateTimeField(auto_now=True)

    @classmethod
    def create(cls, username, email, password):
        user = DjangoUser.objects.create_user(username = username, email = email, password = password)
        return cls(user = user)

    def __str__(self) -> str:
        return self.user.username

class EventList(models.Model):
    name = models.CharField(max_length=100, unique=True)
    creation_date = models.DateField(auto_now_add=True)
    last_updated_date = models.DateTimeField(auto_now=True)
    users = models.ManyToManyField(User, blank = True)

    def __str__(self) -> str:
        return self.name

class Event(models.Model):
    name = models.CharField(max_length=100)
    event_list = models.ForeignKey(EventList, unique = False, on_delete=models.CASCADE)
    description = models.TextField()
    creator = models.ForeignKey(User, unique = False, on_delete=models.PROTECT)
    date = models.DateTimeField()
    creation_date = models.DateField(auto_now_add=True)
    last_updated_date = models.DateTimeField(auto_now=True)
    completed = models.BooleanField(default=False, blank = True)
    notes = models.TextField()

    def mark_as_completed(self,username):
        self.notes = 'List'+ self.event_list.name +'This has been checked by ' + username + ' at ' + str(datetime.datetime.now())
        self.completed = True
        self.save()
    def __str__(self) -> str:
        return self.name + ' ' + str(self.date)

event_manager/deploy/eventlist/forms.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from .models import EventList, Event


class LoginForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(
        attrs={
            "placeholder": "Username",
            "class": "form-control"
        }
    ))
    password = forms.CharField(widget=forms.PasswordInput(
        attrs={
            "placeholder": "Password",
            "class": "form-control"
        }
    ))


class SignUpForm(UserCreationForm):
    username = forms.CharField(widget=forms.TextInput(
        attrs={
            "placeholder": "Username",
            "class": "form-control"
        }
    ))
    email = forms.EmailField(widget=forms.EmailInput(
        attrs={
            "placeholder": "Email",
            "class": "form-control"
        }
    ))
    password1 = forms.CharField(widget=forms.PasswordInput(
        attrs={
            "placeholder": "Password",
            "class": "form-control"
        }
    ))
    password2 = forms.CharField(widget=forms.PasswordInput(
        attrs={
            "placeholder": "Password check",
            "class": "form-control"
        }
    ))

    class Meta:
        model = User
        fields = (
            'username',
            'email',
            'password1',
            'password2'
        )

class addListForm(forms.Form):
    name = forms.CharField(widget=forms.TextInput(
        attrs={
            "placeholder": "Name",
            "class": "form-control"
        }
    ))

class addEventForm(forms.Form):
    name = forms.CharField(widget=forms.TextInput(
        attrs={
            "placeholder": "Name",
            "class": "form-control",
        }
    ))

    date = forms.DateTimeField(widget=forms.DateTimeInput(
        attrs={
            "placeholder": "Date",
            "class": "form-control",
            "type": "datetime-local"
        }
    ))

    description = forms.CharField(required = False, widget=forms.TextInput(
        attrs={
            "placeholder": "Description",
            "class": "form-control",
        }
    ))

class EditListForm(forms.ModelForm):
    class Meta:
        model = EventList
        fields = ['name', 'users']

class EditEventForm(forms.ModelForm):

    description = forms.CharField(required = False, widget=forms.Textarea(
         attrs={
            "class": "form-control",
        }
    ))

    date = forms.DateTimeField(widget=forms.DateTimeInput(
        attrs={
            "class": "form-control",
            "type": "datetime-local"
        }
    ))

    class Meta:
        model = Event
        fields = ['name', 'description', 'date']

event_manager/deploy/eventlist/views.py
# Django imports
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User as DjangoUser
from django.core.exceptions import ObjectDoesNotExist
from django.views.generic import TemplateView

# Django rest framework imports
from rest_framework import viewsets
from rest_framework import permissions

# Event list imports
from .forms import LoginForm, SignUpForm, addEventForm, addListForm, EditListForm, EditEventForm
from .models import User, Event, EventList
from .serializers import EventListSerializer, EventSerializer



def login_view(request):
    form = LoginForm(request.POST or None)

    msg = None

    if request.method == "POST":

        if form.is_valid():
            username = form.cleaned_data.get("username")
            password = form.cleaned_data.get("password")
            user = authenticate(username=username, password=password)

            if user is None:
                return render(request, "accounts/login.html", {"form": form, "msg": 'Invalid credentials'})

            # If is the first time a user logs create his profile
            try:
                profile = User.objects.all().get(user = user)
            except ObjectDoesNotExist:
                profile = User(user = user)
                profile.save()

            login(request, user)
            return redirect('list_event_lists')

    return render(request, "accounts/login.html", {"form": form, "msg": 'Error validating the form'})

def index(request):
    return render(request,"home/index.html")

@login_required(login_url='/accounts/login/')
def logout_view(request):
    logout(request)
    return render(request,"accounts/logout.html")

@login_required(login_url='/accounts/login/')
def list_event_lists(request):

    user, created = User.objects.get_or_create(user=request.user)
    if request.method == "GET":
        form = addListForm()
        return render(
            request,
            "home/list_event_lists.html",
            {
                "form": form,
                "lists": user.eventlist_set.all()
            }
        )
    
    if request.method == 'POST':
        if not request.user.has_perm('eventlist.add_eventlist'):
            return render(request,"home/403.html")
        form = addListForm(request.POST)
        if form.is_valid():
            event_list = EventList(
                name = form.cleaned_data['name'],
            )
            event_list.save()
            event_list.users.add(User.objects.get(user_id = request.user.id))
            event_list.save()
        return redirect(list_event_lists)


@login_required(login_url='/accounts/login/')
def detail_event_list(request, list_name):


    user, created = User.objects.get_or_create(user=request.user)
    event_list = get_object_or_404(EventList, name = list_name)

    if user not in event_list.users.all():
        return render(request,"home/403.html")

    if request.method == 'GET': 
        form = addEventForm()
        return render(
            request,
            "home/event_list.html",
            {
                "form": form,
                "list": event_list,
            }
        )

    if request.method == 'POST':
        if not request.user.has_perm('eventlist.add_event'):
            return render(request,"home/403.html")
        form = addEventForm(request.POST)
        if form.is_valid():
            event = Event(
                name = form.cleaned_data['name'],
                date = form.cleaned_data['date'],
                description = form.cleaned_data['description'],
                event_list = event_list,
                creator = User.objects.get(user_id = request.user.id)
            )
            event.save()
        return redirect('list_events', list_name = list_name)


@login_required(login_url='/accounts/login/')
def profile(request):

    user, created = User.objects.get_or_create(user=request.user)

    if request.method == 'GET':
        return render(
            request,
            'home/profile.html',
            {
                'change_password_form':PasswordChangeForm(request.user),
                'profile': user,
                'events':Event.objects.all().filter(creator = user).order_by('-creation_date')
            }
        )
    if request.method == 'POST':
        if not request.user.has_perm('eventlist.change_user'):
            return render(request,"home/403.html")
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            return redirect('profile')

@login_required(login_url='/accounts/login/')
def delete_list_confirmation(request, list_name):
    
    if not request.user.has_perm('eventlist.delete_eventlist'):
            return render(request,"home/403.html")
    event_list = get_object_or_404(EventList, name = list_name)
    user, created = User.objects.get_or_create(user=request.user)

    if created or not event_list.users.filter(id=user.id).exists():
        return render(request, 'home/403.html')

    if(event_list in user.eventlist_set.all()):
        return render(
            request,
            "home/delete_list_confirmation.html",
            {
                "list": event_list,
            }
        )


@login_required(login_url='/accounts/login/')
def delete_list(request, list_name):

    if not request.user.has_perm('eventlist.delete_eventlist'):
            return render(request,"home/403.html")
    event_list = get_object_or_404(EventList, name = list_name)
    user, created = User.objects.get_or_create(user=request.user)

    if created or not event_list.users.filter(id=user.id).exists():
        return render(request, 'home/403.html')

    event_list.delete()
    return redirect('list_event_lists')

@login_required(login_url='/accounts/login/')
def detail_list(request, list_name):

    if not request.user.has_perm('eventlist.change_eventlist'):
            return render(request,"home/403.html")
    event_list = get_object_or_404(EventList, name = list_name)
    user, created = User.objects.get_or_create(user=request.user)

    if created or not event_list.users.filter(id=user.id).exists():
        return render(request, 'home/403.html')

    if request.method == 'GET':
        form = EditListForm(instance = event_list)
        return render(request, 'home/detail_list.html', {'form':form, 'list':event_list})
    if request.method == 'POST':
        form = EditListForm(request.POST, instance = event_list)
        if 'users' not in request.POST:
            return render(request, 'home/detail_list.html', {'form':form, 'list':event_list, 'error': 'You should choose at least one user, otherwise delete the list.'})
        form.save()
    return redirect('list_event_lists')

@login_required(login_url='/accounts/login/')
def detail_event(request, list_name, event_id):

    if not request.user.has_perm('eventlist.change_event'):
        return render(request,"home/403.html")
    event_list = get_object_or_404(EventList, name = list_name)
    event = get_object_or_404(Event, id = event_id)
    user, created = User.objects.get_or_create(user=request.user)

    if created or not event_list.users.filter(id=user.id).exists():
        return render(request, 'home/403.html')

    if event.event_list.id != event_list.id:
        return render(request, 'home/403.html')

    if request.method == 'GET':
        form = EditEventForm(instance = event)
        return render(request, 'home/event_detail.html', {'form':form, 'event':event})
    if request.method == 'POST':
        form = EditEventForm(request.POST, instance = event)
        form.save()
        event = get_object_or_404(Event, id = event_id)
        if 'completed' in request.POST :
            event.completed = True
            event.save()
        else:
            event.completed = False
            event.save()

    return redirect('list_events', list_name = event_list.name) 

@login_required(login_url='/accounts/login/')
def delete_event(request, list_name, event_id):
    
    if not request.user.has_perm('eventlist.delete_event'):
        return render(request,"home/403.html")
    event_list = get_object_or_404(EventList, name = list_name)
    event = get_object_or_404(Event, id = event_id)
    user, created = User.objects.get_or_create(user=request.user)

    if created or not event_list.users.filter(id=user.id).exists():
        return render(request, 'home/403.html')

    event.delete()
    
    return redirect('list_events', list_name = list_name)


@login_required(login_url='/accounts/login/')
def check_event(request, list_name, event_id):
    
    if not request.user.has_perm('eventlist.change_event'):
        return render(request,"home/403.html")
    event_list = get_object_or_404(EventList, name = list_name)
    event = get_object_or_404(Event, id = event_id)
    user, created = User.objects.get_or_create(user=request.user)

    if created or not event_list.users.filter(id=user.id).exists():
        return render(request, 'home/403.html')

    event.mark_as_completed(request.user.username)

    return redirect('list_events', list_name = list_name)
    
# REST interface views
class EventListViewSet(viewsets.ModelViewSet):
    queryset = EventList.objects.all()
    serializer_class = EventListSerializer
    permission_classes = [permissions.IsAuthenticated]

class EventViewSet(viewsets.ModelViewSet):
    queryset = Event.objects.all()
    serializer_class = EventSerializer
    permission_classes = [permissions.IsAuthenticated]


# Error hadler
def page_not_found_view(request, exception):
    return render(request, 'home/404.html', status=404)

event_manager/deploy/eventlist/templates/home/delete_list_confirmation.html
{% extends 'layouts/base.html' %}

{% block content %}
<div class="container-fluid">
    <div class="col-xl-4 col-lg-5 col-md-6 d-flex flex-column mx-auto">
        <div class="card">
            <div class="card-header">
                <div class="row">
                    <h3 class="text-center text-uppercase">Delete {{list.name}}</h3>
                </div>
            </div>    
            <div class="card-body">
                <div class="row d-flex justify-content-center">
                    <div class="col-md-auto text-center">
                        <a href="{% url 'list_event_lists' %}" class="text-uppercase btn bg-gradient-success mr-2">Cancel</a>
                    </div>
                    <div class="col-md-auto text-center">
                        <a href="{% url 'delete_list' list_name=list.name %}" class="text-uppercase btn bg-gradient-danger mr-2">Delete</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


{% endblock content %}

event_manager/deploy/eventlist/templates/home/detail_list.html
{% extends 'layouts/base.html' %}

{% block content %}
<div class="container-fluid">
    <div class="col-xl-4 col-lg-5 col-md-6 d-flex flex-column mx-auto">
        <div class="card">
            <div class="card-header">
                <div class="row">
                    <h3 class="text-center">{{list.name}}</h3>
                </div>
            </div>    
            <div class="card-body">
                {% if error %}
                    <p style="color: #ea0606;">{{ error }}</p>
                {% endif %}
                <div class="row d-flex justify-content-center">
                    <form method="post">{% csrf_token %}
                        <div class="form-group">
                            <label>Name</label>
                            {{form.name}}
                        </div>
                        <div class="form-group">
                            <label>Users</label>
                            {{form.users}}
                        </div>
                        <div class="row">
                            <button type="submit" value="Submit" class="text-uppercase btn bg-gradient-primary w-100">Save</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

event_manager/deploy/eventlist/templates/home/edit_list.html
{% extends 'layouts/base.html' %}

{% block content %}
<div class="container-fluid">
    <div class="col-xl-4 col-lg-5 col-md-6 d-flex flex-column mx-auto">
        <div class="card">
            <div class="card-header">
                <div class="row">
                    <h3 class="text-center">{{list.name}}</h3>
                </div>
            </div>    
            <div class="card-body">
                <div class="row d-flex justify-content-center">
                    <form action="/events/" method="post">{% csrf_token %}
                        <div class="form-group">
                            <label>Name</label>
                            {{form.name}}
                        </div>
                        <div class="form-group">
                            <label>Users</label>
                            {{form.users}}
                        </div>
                        <div class="row">
                            <button type="submit" value="Submit" class="text-uppercase btn bg-gradient-primary w-100">Save</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

event_manager/deploy/eventlist/templates/home/event_detail.html
{% extends 'layouts/base.html' %}

{% block content %}
<div class="container-fluid">
    <div class="col-xl-4 col-lg-5 col-md-6 d-flex flex-column mx-auto">
        <div class="card">
            <div class="card-header">
                <div class="row">
                    <h3 class="text-center">{{event.name}}</h3>
                </div>
            </div>    
            <div class="card-body">
                <div class="row d-flex justify-content-center">
                    <form method="post">{% csrf_token %}
                        <div class="form-group">
                            <label>Name</label>
                            {{form.name}}
                        </div>
                        <div class="form-group">
                            <label>Date</label>
                            {{form.date}}
                        </div>
                        <div class="form-group">
                            <label>Description</label>
                            {{form.description}}
                        </div>  
                        <div class="form-group text-center">
                        <div class="form-check">
                            <input class="form-check-input" type="checkbox" id="completed" name="completed" {% if event.completed %}checked=""{% endif %}>
                            <label class="custom-control-label" for="completed">Completed</label>
                          </div>
                        </div>
                        <div class="row">
                            <button type="submit" value="Submit" class="text-uppercase btn bg-gradient-primary w-100">Save</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

event_manager/deploy/eventlist/templates/home/event_list.html
{% extends 'layouts/base.html' %}

{% block content %}
    <div class="main-content position-relative bg-gray-100 max-height-vh-100 h-100"></div>
    <div class="container-fluid py-4">
        <div class="flex-column mx-auto">
            <div class="card mb-1">
                <div class="card-header">
                    <div class="row  justify-content-center">
                        <h3 class="text-center text-uppercase">{{list.name}}</h3>
                    </div>
                </div>
                <div class="card-body">
                    <div class="row  justify-content-center">
                        <form method="post">
                            {% csrf_token %}
                            <div class="row">
                                <div class="col">
                                    {{ form.name }}
                                </div>
                                <div class="col">
                                    {{ form.date }}
                                </div>
                                <div class="col">
                                    {{ form.description }}
                                </div><div class="col-md-auto">
                                    <input type="submit" class="btn btn-success" value="Add">
                                </div>
                            </div>
                        </form>
                    </div>
                    <div class="row  justify-content-center mt-6">
                        {% if list %}
                            <div class="card">
                                <div class="table-responsive">
                                    <table class="table align-items-center mb-0">
                                        <thead>
                                        <tr>
                                            <th class="text-center text-uppercase text-secondary text-xs font-weight-bolder opacity-7">Name</th>
                                            <th class="text-center text-uppercase text-secondary text-xs font-weight-bolder opacity-7 ps-2">Date</th>
                                            <th class="text-center text-uppercase text-secondary text-xs font-weight-bolder opacity-7">Description</th>
                                            <th class="text-center text-uppercase text-secondary text-xs font-weight-bolder opacity-7">Creator</th>
                                            <th class="text-center text-uppercase text-secondary text-xs font-weight-bolder opacity-7">Actions</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                            {% for event in list.event_set.all %}
                                            <tr>
                                                <td>
                                                  <div class=" justify-content-center text-center px-2 py-1">
                                                    <div>
                                                        <a href="/events/{{list.name}}/{{ event.id }}/">{{ event.name }}</a>
                                                    </div>
                                                  </div>
                                                </td>
                                                <td>
                                                  <p class=" text-center font-weight-bold mb-0">{{ event.date }}</p>
                                                </td>
                                                <td>
                                                    <p class=" text-center font-weight-bold mb-0">{{ event.description }}</p>
                                                </td>
                                                <td>
                                                    <p class=" text-center font-weight-bold mb-0">{{ event.creator.user.username }}</p>
                                                </td>
                                                <td>
                                                    <div class="text-center">
                                                        <span>
                                                            {% if not event.completed %}
                                                            <a class="text-uppercase btn bg-gradient-success mt-2 btn-sm mr-1" href="{% url 'check_event' event_id=event.id list_name=list.name%}">Done</a>
                                                            {% endif %}
                                                            <a class="text-uppercase btn bg-gradient-danger mt-2 btn-sm me-1" href="{% url 'delete_event' event_id=event.id list_name=list.name%}">Delete</a>
                                                        </span>
                                                    </div>
                                                </td>
                                            </tr>
                                            {% endfor %}
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        {% else %}
                            <p>Something went wrong.</p>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

event_manager/deploy/eventlist/templates/home/index.html
{% extends 'layouts/base-fullscreen.html' %}

{% block title %} Dashboard {% endblock title %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <div class="container-fluid mt-2">

      <div class="card-header">
        <h1 class="text-center text-upercase mb-4 display-1">Docker utility to remote work setup</h1>
      </div>

      <div class="card-body">
        <div class="row">
          <div class="col m-2">
            <div class="card h-100" onclick="location.href='https://meet.anibaltfg.es';" style="cursor: pointer;">
              <div class="card-head text-center">
                <img src="/static/assets/img/logos/jitsi-logo.png" width = "" height = "150"></img>
              </div>
              <div class="card-body">
                <h5 class="text-center"> Access to a videocall using its name.  </h5>
              </div>
            </div>
          </div>
          <div class="col m-2">
            <div class="card h-100" onclick="location.href='https://vpn.anibaltfg.es/';" style="cursor: pointer;">
              <div class="card-head text-center">
                <img src="/static/assets/img/logos/wireguard-logo.png" width = "" height = "150"></img>
              </div>
              <div class="card-body">
                  <h5 class="text-center"> VPN dashboard for user credential creation. </h5>
              </div>
            </div>
          </div>
          <div class="col m-2">
            <div class="card h-100" onclick="location.href='https://traefik.anibaltfg.es';" style="cursor: pointer;">
              <div class="card-head text-center">
                <img src="/static/assets/img/logos/traefik-logo.png" width = "" height = "150"></img>
              </div>
              <div class="card-body">
                  <h5 class="text-center"> Check for the status of the reverse proxy. </h5>
              </div>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col m-2">
            <div class="card h-100" onclick="location.href='{% url 'list_event_lists' %}'" style="cursor: pointer;">
              <div class="card-head text-center">
                <img class="mt-4 mb-2" src="/static/assets/img/logos/logo.png" width = "" height = "150"></img>
                <h3 class="text-center text-uppercase">Event list</h3>
              </div>
              <div class="card-body">
                <h5 class="text-center"> Schedule your task and events.  </h5>
              </div>
            </div>
          </div>
          <div class="col m-2">
            <div class="card h-100" onclick="location.href='/admin'" style="cursor: pointer;">
              <div class="card-head text-center">
                <img class="mt-4 mb-2" src="/static/assets/img/logos/admin-page-logo.png" width = "" height = "150"></img>
                <h3 class="text-center text-uppercase">Event list admin page</h3>
              </div>
              <div class="card-body">
                  <h5 class="text-center"> Admin objects from event list. </h5>
              </div>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col m-2">
            <div class="card">
              <div class="card-head text-center">
                <h3>Event manager REST interactive interface</h3>
              </div>
              <div class="card-body">
                <div class="row">
                  <div class="col m-2">
                    <div class="card text-center" onclick="location.href='/api'" style="cursor: pointer;">
                      <h4>Root</h4>
                    </div>
                  </div>
                  <div class="col m-2">
                    <div class="card text-center" onclick="location.href='/api/event'" style="cursor: pointer;">
                      <h4>Events</h4>
                    </div>
                  </div>
                  <div class="col m-2">
                    <div class="card text-center" onclick="location.href='/api/eventlist'" style="cursor: pointer;">
                      <h4>Event lists</h4>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

{% endblock %}